#!/bin/bash

# -----------------------------------------------------------------------------
# Package lists for arch-easyinstall
# -----------------------------------------------------------------------------

# Base system
BASE_PACKAGES=(
    "base"
    "base-devel"
    "linux"
    "linux-firmware"
    "linux-headers"
)

# Essential utilities
EXTRA_PACKAGES=(
    "vim"
    "networkmanager"
    "git"
)